"""
smi_acquire.codegen
===================

Turn a (SampleList, technique, parameters, project metadata) tuple into a **runnable,
copy-pasteable** SMI beamline script.

The generated script is exactly what the README of ``smi_plans`` shows by hand: add the
templates dir to ``sys.path``, import ``SampleList`` + the chosen technique module, build the
bar with ``SampleList.from_columns(...)``, then ``RE(<technique>.<entry>(bar, ...))``.

Nothing here imports bluesky or Panel; it is pure string assembly + the pure-Python sample
model, so it is trivially unit-testable off-beamline.

Later, the same inputs can drive a queueserver submission instead of emitting text -- see
:func:`to_queueserver_item` for the shape that maps onto a ``BPlan``.
"""

from __future__ import annotations

import json
from typing import Any, Dict, Optional

from . import samples as _samples
from . import techniques as _tech


DEFAULT_TEMPLATES_PATH = "/home/xf12id/SWAXS_user_scripts/templates"


# ---------------------------------------------------------------------------
# Sample-list source
# ---------------------------------------------------------------------------
def render_samplelist(samplelist, *, var="bar", project_md=None) -> str:
    """Emit a ``SampleList.from_columns(...)`` block from a SampleList.

    Only columns that are actually used by at least one sample are emitted, so the block stays
    readable. ``incident_angles`` is emitted as a shared list when identical across samples,
    else per-sample.
    """
    rows = list(samplelist)
    names = [s.name for s in rows]

    cols = ["piezo_x", "piezo_y", "piezo_z", "piezo_th",
            "hexa_x", "hexa_y", "hexa_z", "hexa_th"]
    used = {}
    for c in cols:
        vals = [getattr(s, c) for s in rows]
        if any(v is not None for v in vals):
            used[c] = vals

    lines = ["{} = SampleList.from_columns(".format(var)]
    lines.append("    names={!r},".format(names))
    for c, vals in used.items():
        lines.append("    {}={},".format(c, _pylist(vals)))

    # incident_angles: shared if all equal & non-empty, else per-sample list-of-lists
    ia = [list(s.incident_angles) for s in rows]
    if any(ia):
        if all(a == ia[0] for a in ia) and ia[0]:
            lines.append("    incident_angles={},".format(_pylist(ia[0])))
        else:
            lines.append("    incident_angles={},".format(_pylist(ia)))

    # per-sample md (only emit if any sample carries md)
    if any(s.md for s in rows):
        md_list = [dict(s.md) for s in rows]
        lines.append("    md={},".format(_pylist(md_list)))
    elif project_md:
        lines.append("    md={},".format(_pyval(project_md)))

    lines.append(")")
    return "\n".join(lines)


def _pylist(vals):
    return "[" + ", ".join(_pyval(v) for v in vals) + "]"


def _pyval(v):
    if v is None:
        return "None"
    if isinstance(v, float):
        return str(int(v)) if v.is_integer() else repr(v)
    if isinstance(v, (list, tuple)):
        return _pylist(list(v))
    if isinstance(v, dict):
        return "{" + ", ".join("{!r}: {}".format(k, _pyval(val))
                               for k, val in v.items()) + "}"
    return repr(v)


# ---------------------------------------------------------------------------
# Full script
# ---------------------------------------------------------------------------
def generate_script(samplelist, letter: str, values: Optional[Dict[str, Any]] = None, *,
                    project_md: Optional[Dict[str, Any]] = None,
                    templates_path: Optional[str] = None,
                    run: bool = True) -> str:
    """Produce a complete, copy-pasteable beamline script string.

    Parameters
    ----------
    samplelist : SampleList
    letter : str
        Technique letter ("A".."O").
    values : dict
        Parameter values for the technique (missing keys fall back to spec defaults).
    project_md : dict, optional
        Experiment-wide metadata (e.g. ``{"project_name": "311234_Demo"}``).  Applied to the
        bar when no per-sample md is present.
    templates_path : str, optional
        Path inserted on ``sys.path`` so ``import smi_plans`` works.  Defaults to the resolved
        path (if the core found one) or the beamline default.
    run : bool
        If True, wrap the technique call in ``RE(...)``; else just build the plan object.
    """
    values = dict(values or {})
    tpath = templates_path or _samples.RESOLVED_TEMPLATES_PATH or DEFAULT_TEMPLATES_PATH

    spec = _tech.get(letter)
    special = _tech.SPECIAL.get(letter)

    header = [
        '"""Generated by smi-acquire. Review before running on the beamline."""',
        "import sys; sys.path.append({!r})".format(tpath),
        "from smi_plans import SampleList",
    ]

    if spec is not None:
        alias, module, entry = spec.alias, spec.module, spec.entry
        # arc-economy switch for technique B
        if letter == "B" and values.get("arc_economy"):
            entry = "giwaxs_bar_arc_economy"
        header.append("from smi_plans import {} as {}".format(module, alias))
        body = [render_samplelist(samplelist, project_md=project_md)]
        setup = spec.render_setup(values)
        if setup:
            body += [""] + setup
        # rebuild call honoring possibly-swapped entry
        r = spec.rendered(values)
        call = "{a}.{e}({args})".format(a=alias, e=entry,
                                        args=spec.call_template.format(**r))
        body.append("")
        body.append("RE({})".format(call) if run else "plan = {}".format(call))
        needs = spec.needs
        notes = spec.notes
    elif special is not None:
        alias, module = special["alias"], special["module"]
        header.append("from smi_plans import {} as {}".format(module, alias))
        body = [render_samplelist(samplelist, project_md=project_md), "",
                "# --- {} ---".format(special["title"]),
                special["template"]]
        needs = []
        notes = special.get("summary", "")
    else:
        raise KeyError("Unknown technique letter: {!r}".format(letter))

    parts = ["\n".join(header), "", "\n".join(body)]
    footer = []
    if needs:
        footer.append("# Requires at runtime: " + ", ".join(needs))
    if notes:
        footer.append("# Note: " + notes)
    if footer:
        parts += ["", "\n".join(footer)]
    return "\n".join(parts).rstrip() + "\n"


# ---------------------------------------------------------------------------
# Future: queueserver item shape (stub, not yet wired)
# ---------------------------------------------------------------------------
def to_queueserver_item(samplelist, letter, values=None, *, project_md=None) -> Dict[str, Any]:
    """Return a dict approximating a queueserver ``BPlan`` item for the chosen technique.

    This is the seam where the "emit a script" step is later replaced by submitting to the
    qserver REST API.  Kept deliberately simple: name = entry point, kwargs = sample dicts +
    rendered params.  (The sample bar is serialized as ``from_dicts`` input.)
    """
    spec = _tech.get(letter)
    if spec is None:
        raise KeyError("Technique {!r} has no bar entry point for queueserver".format(letter))
    vals = {**spec.defaults(), **(values or {})}
    return {
        "name": spec.entry,
        "args": [],
        "kwargs": {
            "samples": samplelist.to_dicts(),
            "project_md": project_md or {},
            **{k: v for k, v in vals.items() if k != "arc_economy"},
        },
        "item_type": "plan",
    }


__all__ = ["generate_script", "render_samplelist", "to_queueserver_item",
           "DEFAULT_TEMPLATES_PATH"]
