"""Generate paste-ready, complete bluesky-plan snippets.

Every snippet is a self-contained ``def name(...):`` that the user can paste into a longer
script. Each defines ``dets`` inline and uses ``yield from bp.<plan>`` so the function works
naturally when called with ``RE(<plan>())``.

Naming convention
-----------------
- **Bookmark** scans use a ``filename_signal = Signal(name='filename_template')`` placed
  inside ``dets``. The bookmark's per-spot name is the value driven into that signal at each
  step, and the md template ``{'sample_name': '{filename_template}'}`` causes the
  downstream file-name builder to read the signal at every event.
- **Bulk** scans (polygon, square) use a motor-position template directly:
  ``{'sample_name': name + '_x{piezo_x}_y{piezo_y}'}`` — the ``{piezo_x}`` / ``{piezo_y}``
  placeholders are expanded by the file-name builder from the motor readback at each event.
- **Linear** (knife-edge) alignment scans wrap the mode swaps inside the plan with
  ``yield from smi.modeAlignment()`` / ``modeMeasurement()`` so a single
  ``RE(knife_edge_x_alignment())`` does the whole alignment.
"""

from __future__ import annotations

from dataclasses import dataclass

from .config import ScriptsConfig


@dataclass
class Bookmark:
    """In-memory bookmark — a saved sample position.

    Three independent flags decide how it participates:

    - ``is_reference``: a config-persisted landmark (visible on the image but *never*
      scanned). References ignore ``in_scan``.
    - ``in_scan``: whether this (regular) bookmark is currently a scan target. Toggled
      per-bookmark from the scan panels' target list and the bookmark table's ``scan``
      column. Defaults to ``True`` so newly added points are scanned unless opted out.
    - click-placed points are ordinary bookmarks named ``pos1``/``pos2``/… with
      ``in_scan=True``; nothing distinguishes them except the name.
    """

    name: str
    x: float
    y: float
    z: float
    is_reference: bool = False
    in_scan: bool = True


def _fmt(v: float) -> str:
    return f"{v:.4f}"


def _detectors_repr(detectors: list[str], extra: list[str] | None = None) -> str:
    items = list(detectors)
    if extra:
        items.extend(extra)
    return "[" + ", ".join(items) + "]"


def _motor_template(motor_object: str) -> str:
    """``{piezo_x}_y{piezo_y}`` style suffix used in the sample_name md template."""
    return "_x{" + motor_object + "_x}_y{" + motor_object + "_y}"


def _scan_bookmarks(bookmarks: list[Bookmark]) -> list[Bookmark]:
    """The targets that participate in generated scans.

    Drops references (never scanned) and any regular bookmark whose ``in_scan`` flag is
    off. The same generators serve real bookmarks *and* click-placed points (passed in as
    non-reference :class:`Bookmark` objects with ``in_scan=True``).
    """
    return [b for b in bookmarks if not b.is_reference and b.in_scan]


# Per-point dwell assumption used for scan-time estimates shown in the UI. Bookmark-only list
# scans aren't estimated (the operator drives those interactively), so this only applies to
# the square / polygon / linear grid+line scans.
SECONDS_PER_POINT = 3.0


def format_duration(seconds: float) -> str:
    """Human-friendly ``h/m/s`` duration string for a scan-time estimate."""
    seconds = max(0.0, float(seconds))
    total = int(round(seconds))
    h, rem = divmod(total, 3600)
    m, s = divmod(rem, 60)
    if h:
        return f"{h}h {m:02d}m {s:02d}s"
    if m:
        return f"{m}m {s:02d}s"
    return f"{s}s"


def estimate_label(total_points: int) -> str:
    """``est. ~Xs (N pts × 3s)`` label, or empty string when there's nothing to estimate."""
    if total_points <= 0:
        return ""
    secs = total_points * SECONDS_PER_POINT
    return f"est. ~{format_duration(secs)}  ({total_points:,} pts × {SECONDS_PER_POINT:g}s)"


def bookmark_list_scan_snippet(
    bookmarks: list[Bookmark],
    scripts_cfg: ScriptsConfig,
) -> str:
    """Bookmark scan: ``bp.list_scan`` over correlated (x,y,z) triples with named filenames."""
    bookmarks = _scan_bookmarks(bookmarks)
    if not bookmarks:
        return "# no bookmarks selected for scanning — add one and tick its 'scan' box\n"

    mot = scripts_cfg.motor_object
    filename_sig_name = scripts_cfg.filename_signal_name
    dets_repr = _detectors_repr(scripts_cfg.detectors, extra=["filename_signal"])

    names_repr = ", ".join(repr(b.name) for b in bookmarks)
    xs_repr = ", ".join(_fmt(b.x) for b in bookmarks)
    ys_repr = ", ".join(_fmt(b.y) for b in bookmarks)
    zs_repr = ", ".join(_fmt(b.z) for b in bookmarks)

    return (
        "def bookmark_scan():\n"
        "    # Auto-generated by swaxs-beam-image (bookmark mode)\n"
        f"    # scan over {len(bookmarks)} samples chosen interactively via on-axis microscope\n"
        "    from ophyd import Signal\n"
        f"    filename_signal = Signal(name={filename_sig_name!r})\n"
        f"    dets = {dets_repr}\n"
        "\n"
        f"    bookmark_names = [{names_repr}]\n"
        f"    xs = [{xs_repr}]   # motor units\n"
        f"    ys = [{ys_repr}]   # motor units\n"
        f"    zs = [{zs_repr}]   # motor units\n"
        "\n"
        "    yield from bp.list_scan(\n"
        "        dets,\n"
        f"        {mot}.x, xs,\n"
        f"        {mot}.y, ys,\n"
        f"        {mot}.z, zs,\n"
        "        filename_signal, bookmark_names,\n"
        f"        md={{'sample_name': '{{{filename_sig_name}}}'}}, "
        f"# optionally add '{_motor_template(mot)}' to include motor positions\n"
        "    )\n"
    )


def area_list_scan_snippet(
    points: list[tuple[float, float, float]],
    scripts_cfg: ScriptsConfig,
    plan_func_name: str = "polygon_scan",
    sample_name: str = "sample1",
) -> str:
    """Polygon scan: ``bp.list_scan`` over polygon-filtered (x,y,z) points.

    Uses a motor-position-templated filename (no per-point filename signal) because the
    point set is generated geometrically, not named by the operator.
    """
    if not points:
        return "# polygon contained no grid points\n"

    mot = scripts_cfg.motor_object
    dets_repr = _detectors_repr(scripts_cfg.detectors)

    xs_repr = ", ".join(_fmt(p[0]) for p in points)
    ys_repr = ", ".join(_fmt(p[1]) for p in points)
    zs_repr = ", ".join(_fmt(p[2]) for p in points)
    template_tail = _motor_template(mot)

    return (
        f"def {plan_func_name}(name={sample_name!r}):\n"
        "    # Auto-generated by swaxs-beam-image (Scan → Polygon)\n"
        f"    # polygon-filtered list scan: {len(points)} points\n"
        f"    dets = {dets_repr}\n"
        "\n"
        f"    xs = [{xs_repr}]   # motor units\n"
        f"    ys = [{ys_repr}]   # motor units\n"
        f"    zs = [{zs_repr}]   # motor units\n"
        "\n"
        "    yield from bp.list_scan(\n"
        "        dets,\n"
        f"        {mot}.x, xs,\n"
        f"        {mot}.y, ys,\n"
        f"        {mot}.z, zs,\n"
        f"        md={{'sample_name': name+'{template_tail}'}},  "
        "# template for the filename — motor positions appended at each step\n"
        "    )\n"
    )


def square_grid_scan_snippet(
    cx: float,
    cy: float,
    width: float,
    height: float,
    nx: int,
    ny: int,
    scripts_cfg: ScriptsConfig,
    plan_func_name: str = "grid_scan",
    sample_name: str = "sample1",
) -> str:
    """Square scan: compact ``bp.grid_scan`` over an outer-y / inner-x rectangle."""
    mot = scripts_cfg.motor_object
    dets_repr = _detectors_repr(scripts_cfg.detectors)
    x0 = cx - width / 2.0
    x1 = cx + width / 2.0
    y0 = cy - height / 2.0
    y1 = cy + height / 2.0
    template_tail = _motor_template(mot)

    return (
        f"def {plan_func_name}(name={sample_name!r}):\n"
        "    # Auto-generated by swaxs-beam-image (Scan → Square)\n"
        f"    # grid scan: {ny}×{nx} = {nx * ny} points\n"
        f"    dets = {dets_repr}\n"
        "\n"
        "    yield from bp.grid_scan(\n"
        "        dets,\n"
        f"        {mot}.y, {_fmt(y0)}, {_fmt(y1)}, {ny},   # outer (slow) axis\n"
        f"        {mot}.x, {_fmt(x0)}, {_fmt(x1)}, {nx},   # inner (fast) axis\n"
        f"        md={{'sample_name': name+'{template_tail}'}},  "
        "# template for the filename — motor positions appended at each step\n"
        "    )\n"
    )


def line_scan_snippet(
    motor_axis: str,
    start: float,
    stop: float,
    num: int,
    orthogonal_axis: str,
    orthogonal_value: float,
    scripts_cfg: ScriptsConfig,
) -> str:
    """Linear/knife-edge alignment: full plan including mode swaps."""
    mot = scripts_cfg.motor_object
    dets_repr = _detectors_repr(scripts_cfg.alignment_detectors)
    template_tail = "_x{" + f"{mot}_{motor_axis}" + "}"
    default_name = f"knife_edge_{motor_axis}"
    func_name = f"knife_edge_{motor_axis}_alignment"

    lines = [
        f"def {func_name}(name={default_name!r}):",
        "    # Auto-generated by swaxs-beam-image (Linear scan)",
        f"    # knife-edge alignment along {motor_axis} ({num} points)",
        f"    dets = {dets_repr}",
        "",
    ]
    if scripts_cfg.alignment_pre:
        lines.append(f"    yield from {scripts_cfg.alignment_pre}")
    lines.append(
        f"    yield from bps.mv({mot}.{orthogonal_axis}, {_fmt(orthogonal_value)})"
    )
    lines.append(
        f"    yield from bp.scan(\n"
        f"        dets,\n"
        f"        {mot}.{motor_axis}, {_fmt(start)}, {_fmt(stop)}, {num},\n"
        f"        md={{'sample_name': name+'{template_tail}'}},\n"
        f"    )"
    )
    if scripts_cfg.alignment_post:
        lines.append(f"    yield from {scripts_cfg.alignment_post}")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------------------
# Multi-bookmark scans
# ---------------------------------------------------------------------------------------
#
# These build a *single* outer plan that sequences one scan per (non-reference) bookmark.
# A shared shape (square dimensions, polygon offsets, or line length/axis) is replicated,
# centered on each bookmark, and each scan's ``sample_name`` is seeded from the bookmark's
# own name so the generated files are named after the sample the operator picked.


def square_grid_scans_at_bookmarks(
    bookmarks: list[Bookmark],
    width: float,
    height: float,
    nx: int,
    ny: int,
    scripts_cfg: ScriptsConfig,
    plan_func_name: str = "all_square_scans",
) -> str:
    """One outer plan running an identical ``width × height`` grid centered on each bookmark.

    The bookmark name is used as the per-scan filename base.
    """
    bms = _scan_bookmarks(bookmarks)
    if not bms:
        return (
            "# no square scans yet — tick a bookmark's 'scan' box in the Bookmarks list, or use 'Add point'\n"
        )
    if not (width > 0 and height > 0 and nx >= 1 and ny >= 1):
        return "# set a positive width, height, and step to populate this script\n"

    mot = scripts_cfg.motor_object
    dets_repr = _detectors_repr(scripts_cfg.detectors)
    template_tail = _motor_template(mot)
    hw = width / 2.0
    hh = height / 2.0

    samples_repr = ",\n".join(
        f"        ({b.name!r}, {_fmt(b.x)}, {_fmt(b.y)}, {_fmt(b.z)})" for b in bms
    )

    return (
        f"def {plan_func_name}():\n"
        "    # Auto-generated by swaxs-beam-image (Scan → Square)\n"
        f"    # identical {ny}×{nx} = {nx * ny}-point grid centered on each of "
        f"{len(bms)} target(s)\n"
        f"    dets = {dets_repr}\n"
        "\n"
        "    # (name, center_x, center_y, z) per target — motor units\n"
        "    samples = [\n"
        f"{samples_repr},\n"
        "    ]\n"
        "\n"
        "    for name, cx, cy, z in samples:\n"
        f"        yield from bps.mv({mot}.z, z)\n"
        "        yield from bp.grid_scan(\n"
        "            dets,\n"
        f"            {mot}.y, cy - {_fmt(hh)}, cy + {_fmt(hh)}, {ny},   # outer (slow) axis\n"
        f"            {mot}.x, cx - {_fmt(hw)}, cx + {_fmt(hw)}, {nx},   # inner (fast) axis\n"
        f"            md={{'sample_name': name+'{template_tail}'}},\n"
        "        )\n"
    )


def polygon_scans_at_bookmarks(
    bookmarks: list[Bookmark],
    offsets: list[tuple[float, float]],
    scripts_cfg: ScriptsConfig,
    plan_func_name: str = "all_polygon_scans",
) -> str:
    """One outer plan running an identical polygon-filtered point set centered on each bookmark.

    ``offsets`` are the grid points expressed *relative to the polygon centroid* so the same
    shape can be re-centered on every bookmark. The bookmark name is the per-scan filename base.
    """
    bms = _scan_bookmarks(bookmarks)
    if not bms:
        return (
            "# no polygon scans yet — tick a bookmark's 'scan' box in the Bookmarks list (with a polygon drawn)\n"
        )
    if not offsets:
        return "# draw a polygon to populate this script\n"

    mot = scripts_cfg.motor_object
    dets_repr = _detectors_repr(scripts_cfg.detectors)
    template_tail = _motor_template(mot)

    dx_repr = ", ".join(_fmt(o[0]) for o in offsets)
    dy_repr = ", ".join(_fmt(o[1]) for o in offsets)
    samples_repr = ",\n".join(
        f"        ({b.name!r}, {_fmt(b.x)}, {_fmt(b.y)}, {_fmt(b.z)})" for b in bms
    )

    return (
        f"def {plan_func_name}():\n"
        "    # Auto-generated by swaxs-beam-image (Scan → Polygon)\n"
        f"    # identical {len(offsets)}-point polygon grid centered on each of "
        f"{len(bms)} target(s)\n"
        f"    dets = {dets_repr}\n"
        "\n"
        "    # grid points relative to each target center — motor units\n"
        f"    dxs = [{dx_repr}]\n"
        f"    dys = [{dy_repr}]\n"
        "\n"
        "    # (name, center_x, center_y, z) per target — motor units\n"
        "    samples = [\n"
        f"{samples_repr},\n"
        "    ]\n"
        "\n"
        "    for name, cx, cy, z in samples:\n"
        "        xs = [cx + dx for dx in dxs]\n"
        "        ys = [cy + dy for dy in dys]\n"
        "        zs = [z] * len(xs)\n"
        "        yield from bp.list_scan(\n"
        "            dets,\n"
        f"            {mot}.x, xs,\n"
        f"            {mot}.y, ys,\n"
        f"            {mot}.z, zs,\n"
        f"            md={{'sample_name': name+'{template_tail}'}},\n"
        "        )\n"
    )


def line_scans_at_bookmarks(
    bookmarks: list[Bookmark],
    motor_axis: str,
    distance: float,
    num: int,
    scripts_cfg: ScriptsConfig,
    plan_func_name: str = "all_line_scans",
) -> str:
    """One outer plan running an identical centered line scan along ``motor_axis`` at each bookmark.

    The line spans ``±distance/2`` about the bookmark center on the chosen axis, holding the
    orthogonal axis at the bookmark value. The bookmark name is the per-scan filename base.
    """
    bms = _scan_bookmarks(bookmarks)
    if not bms:
        return (
            "# no line scans yet — tick a bookmark's 'scan' box in the Bookmarks list, or use 'Add point'\n"
        )
    if not (distance > 0 and num >= 2):
        return "# set a positive distance and ≥2 points to populate this script\n"

    mot = scripts_cfg.motor_object
    dets_repr = _detectors_repr(scripts_cfg.alignment_detectors)
    orth_axis = "y" if motor_axis == "x" else "x"
    template_tail = "_x{" + f"{mot}_{motor_axis}" + "}"
    half = distance / 2.0

    samples_repr = ",\n".join(
        f"        ({b.name!r}, {_fmt(b.x)}, {_fmt(b.y)}, {_fmt(b.z)})" for b in bms
    )

    lines = [
        f"def {plan_func_name}():",
        "    # Auto-generated by swaxs-beam-image (Scan → Linear)",
        f"    # identical {num}-point line scan along {motor_axis} centered on each of "
        f"{len(bms)} target(s)",
        f"    dets = {dets_repr}",
        "",
        "    # (name, x, y, z) per target — motor units",
        "    samples = [",
        samples_repr + ",",
        "    ]",
        "",
    ]
    if scripts_cfg.alignment_pre:
        lines.append(f"    yield from {scripts_cfg.alignment_pre}")
    lines.append("    for name, x, y, z in samples:")
    center_var = "x" if motor_axis == "x" else "y"
    lines.append(f"        yield from bps.mv({mot}.{orth_axis}, {orth_axis}, {mot}.z, z)")
    lines.append("        yield from bp.scan(")
    lines.append("            dets,")
    lines.append(
        f"            {mot}.{motor_axis}, {center_var} - {_fmt(half)}, "
        f"{center_var} + {_fmt(half)}, {num},"
    )
    lines.append(f"            md={{'sample_name': name+'{template_tail}'}},")
    lines.append("        )")
    if scripts_cfg.alignment_post:
        lines.append(f"    yield from {scripts_cfg.alignment_post}")
    lines.append("")
    return "\n".join(lines)
